// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.remote.BrowserType;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.net.URL;
import java.util.*;
public class TestSuite3Test {
  //private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  private static final String ACCESS_KEY = "eyJ4cC59Ijo0MjQwMjk1LCJ4cC5wIjo0MjQwMjk0LCJ4cC5tIjoiTVRVME9EQTJPREU1T1Rrek5RIiwiYWxnIjoiSFMyNTYifQ.eyJleHAiOjE4NjM1MDg5MDUsImlzcyI6ImNvbS5leHBlcml0ZXN0In0.JsahW8N-gWkTIU3WC1UMV-oI8_xQnnFaptdrB3wIjzQ";
  private RemoteWebDriver driver;
  private URL url;
  private DesiredCapabilities dc = new DesiredCapabilities();

  @Before
  public void setUp() throws Exception {

    //System.setProperty("webdriver.gecko.driver", "C:\\Users\\mbabilo\\Desktop\\recorder\\geckodriver.exe"); // <-- Change this path

    url = new URL("https://cloud.seetest.io/wd/hub");
    dc.setCapability(CapabilityType.BROWSER_NAME, BrowserType.FIREFOX);

    dc.setCapability(CapabilityType.PLATFORM, Platform.ANY);
    dc.setCapability("accessKey", ACCESS_KEY);
    dc.setCapability("testName", "Test suite 3");
    driver = new RemoteWebDriver(url, dc);

    //driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    // Test name: test1
    // Step # | name | target | value | comment
    // 1 | open | / |  |
    driver.get("https://experitest.com//");
    // 2 | setWindowSize | 1936x1056 |  |
    driver.manage().window().setSize(new Dimension(1936, 1056));
    // 3 | click | linkText=LEARN MORE |  |
    driver.findElement(By.linkText("LEARN MORE")).click();
    // 4 | storeText | css=h1 | myVar |
    vars.put("myVar", driver.findElement(By.cssSelector("h1")).getText());
    // 5 | if | ${myVar} === "Cross Browser Testing" |  |
    if ((Boolean) js.executeScript("return (arguments[0] === 'Cross Browser Testing')", vars.get("myVar"))) {
      // 6 | clickAt | css=.page-btn > a |  |
      driver.findElement(By.cssSelector(".page-btn > a")).click();
      // 7 | else |  |  |
    } else {
      // 8 | clickAt | linkText=LEARN MORE |  |
      driver.findElement(By.linkText("LEARN MORE")).click();
      // 9 | end |  |  |
    }
  }
  @Test
  public void test2() {
    // Test name: test2
    // Step # | name | target | value | comment
    // 1 | open | / |  |
    driver.get("https://experitest.com//");
    // 2 | setWindowSize | 1936x1056 |  |
    driver.manage().window().setSize(new Dimension(1936, 1056));
    // 3 | click | css=.col-sm-8 a |  |
    driver.findElement(By.cssSelector(".col-sm-8 a")).click();
    // 4 | storeText | css=h1 | myVar |
    vars.put("myVar", driver.findElement(By.cssSelector("h1")).getText());
    // 5 | if | ${myVar} === "Cross Browser Testing" |  |
    if ((Boolean) js.executeScript("return (arguments[0] === 'Cross Browser Testing')", vars.get("myVar"))) {
      // 6 | clickAt | css=.page-btn > a |  |
      driver.findElement(By.cssSelector(".page-btn > a")).click();
      // 7 | else |  |  |
    } else {
      // 8 | clickAt | linkText=LEARN MORE |  |
      driver.findElement(By.linkText("LEARN MORE")).click();
      // 9 | end |  |  |
    }
  }
}
